version: "3"
services:
  backend:
    privileged: true
    network_mode: host # --network host
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - shared-data:/etc/v2ray
      - ./service:/service:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  v2ray:
    privileged: true
    network_mode: host # --network host
    pid: service:backend
    restart: always
    image: "v2fly/v2fly-core"
    environment:
      - V2RAY_LOCATION_ASSET=/etc/v2ray
    volumes:
      - shared-data:/etc/v2ray
    entrypoint: sh -c "cp -rfu /usr/bin/v2ray/* /etc/v2ray/ && v2ray -config=/etc/v2ray/config.json"

volumes:
  shared-data:
