name: v2raya-nightly-docker

on:
  push:
    branches: [ master ]

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - uses: actions/checkout@v2      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the Docker image
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          v=$(git log --pretty=format:"%ad" --date=format:%Y%m%d $(git show -s --format=%H) -1)
          docker buildx build -t mzz2017/v2raya-nightly:$v -f Dockerfile.nightly --platform=linux/arm,linux/arm64,linux/amd64 . --push
          docker buildx build -t mzz2017/v2raya-nightly:latest -f Dockerfile.nightly --platform=linux/arm,linux/arm64,linux/amd64 . --push
